### ISSUE TITLE
Star Players

### ISSUE THREAD

**Issue by Melifaxis** [jonasbusk/nuflheim#1]
I love the sheet.  Unless I am missing something you can't add Star Players to a roster.

**Comment by jonasbusk** [comment]
Great, I am glad you like it. And thank you for providing feedback! Adding Star Players is on my todo list already, but I think it will be a rather large task to type them all in and create a good UI for it. So I can't say when it will be ready, but stay tuned.

**Comment by Melifaxis** [comment]
If you provide me an Excel or Google Sheets format that you would like I can type them in for you.

**Comment by jonasbusk** [comment]
Thanks a lot for helping out! Any format will do, as long as it is well structured. Perhaps someone has already made a spreadsheet roster with star players? That could save some work. I have not looked into that.

**Comment by Melifaxis** [comment]
I didn't find one, but here is a Google Sheet with all of them.  If you need edit access just let me know, but you can also just make a copy of it and get edit access by default on your copy.

https://docs.google.com/spreadsheets/d/1yGiRDvUDE6dsJJgzlrx-tKvnUeHK_euxKp3Htw6WitU/edit?usp=sharing

**Comment by jonasbusk** [comment]
Thanks for the help! I'm quite busy with other projects at the moment, but I'll get back to this.

**Comment by jonasbusk** [comment]
I finally got around to adding the Star Players. Thanks a lot for the help!

**Comment by Melifaxis** [comment]
Great news!  You are very welcome.  Thanks for the update!
    On Sunday, November 7, 2021, 08:21:30 AM EST, Jonas Busk ***@***.***> wrote:  
 
 


I finally got around to adding the Star Players. Thanks a lot for the help!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
