### ISSUE TITLE
Add Skills To Separate Page

### ISSUE THREAD

**Issue by SpaceModulator2019** [jonasbusk/nuflheim#2]
Love the generator! Would it be possible to add a second page that includes all of the skills you have + their descriptions?

**Comment by jonasbusk** [comment]
Thank you for the suggestion! That would be a very useful addition, but also a little bit heavy on typing and maintenance and there could be copyright issues. I will think about it.

**Comment by jonasbusk** [comment]
Duplicate of #4.
