### ISSUE TITLE
Star Players Bomber Dribblesnot and Fungus The Loon are missing

### ISSUE THREAD

**Issue by EamboToo** [jonasbusk/nuflheim#3]
Hi Love the team builder. I just noticed that the bomber and fungus star players aren't showing up for any of the Badlands Brawl and Underworld Challenge teams.

**Comment by jonasbusk** [comment]
I am glad you like it! Thanks a lot for pointing this out. I have updated the star player list, so now it should be up to date. Please let me know if you spot any other mistakes.
