### ISSUE TITLE
PDF download - Chosen Skills colour

### ISSUE THREAD

**Issue by EamboToo** [jonasbusk/nuflheim#5]
Hi, would it be possible to have any chosen additional skills to be a different colour, like Blue, on the PDF download. It would just be handier for tournaments if you could see any extra skills players have at a glance. Just like it does in the builder.

Thanks
E

**Comment by jonasbusk** [comment]
Actually I was not too happy with the different coloured skills, so instead I have marked primary skills with an asterisk (*) and secondary skills with two asterisks (**), both on the website and in the pdf. I hope you will find this change useful.
